FROM nginx:1.15.8-alpine

#Config
COPY ./nginx.conf /etc/nginx/nginx.conf

#Content
COPY ./*.html /usr/share/nginx/html
#copy ./*.css /usr/share/nginx/html/
#copy ./*.png /usr/share/nginx/html/
#copy ./*.js /usr/share/nginx/html/
