version: "3.7"
   
services:
  backend:
    container_name: p2b
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - target: 5000
        published: 5000
    networks:
      - webapp-net
    environment:
      SECRET_KEY: ./backend/backend/.env

  frontend:
    container_name: p2f
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - target: 3000
        published: 3000
    networks:
      - webapp-net

networks:
  webapp-net: