name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
#    - uses: actions/checkout@v3
#    - name: Build the Docker image
#      run: cd prueba3 && docker build . --file Dockerfile --tag nginx-ci:$(date +%s)
#    - uses: mr-smithers-excellent/docker-build-push@v5    
#      with:
#        image: feedehc/nginx-ci
#        directory: prueba3
#        dockerfile: ./prueba3/Dockerfile
#        registry: docker.io
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          TAG_NAME: "v0.1.0"
          BUILDX: "true"
