name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
#    - uses: actions/checkout@v3
#    - name: Build the Docker image
#      run: cd prueba3 && docker build . --file Dockerfile --tag nginx-ci:$(date +%s)
#    - uses: mr-smithers-excellent/docker-build-push@v5    
#      with:
#        image: feedehc/nginx-ci
#        directory: ./prueba3
#        registry: docker.io
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: prueba3
          push: true
          tags: feedehc/nginx-ci:latest
