name: Docker Image CI

on:
  push:
    #branches: [ master ]
    paths:
      - 'prueba3/index.html'
  #pull_request:
    #branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
#    - uses: actions/checkout@v3
#    - name: Build the Docker image
#      run: cd prueba3 && docker build . --file Dockerfile --tag nginx-ci:$(date +%s)
#    - uses: mr-smithers-excellent/docker-build-push@v5    
#      with:
#        image: feedehc/nginx-ci
#        directory: prueba3
#        dockerfile: ./prueba3/Dockerfile
#        registry: docker.io
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:prueba3"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx-ci:latest
